name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          [windows, ubuntu]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ matrix.os }}
        path: ./target/release
        warn: Failed uploading artifacts
        retention-days: 90
